//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ICANDI.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_CUSTOM_PRO_IMAGE            101
#define IDC_CUSTOM_ORI_IMAGE            102
#define IDC_CUSTOM_GOMSC                103
#define IDC_CUSTOM_RAW_VIDEO            104
#define IDC_CUSTOM_DEWARP_VIDEO         105
#define IDC_CUSTOM_STIMULUS_STATUS      106
#define IDC_CUSTOM_LBL_WHITE            107
#define IDC_CUSTOM_LBL_BLACK            108
#define IDL_VIDEO_FILENAME              109
#define IDE_VIDEO_FILENAME              110
#define IDE_VIDEO_FOLDER                111
#define IDL_VIDEO_FOLDER                112
#define IDC_CUSTOM_TIME_ELAPSE          113
#define IDC_MATROX_PARAMETER            114
#define ID_SAVE_VIDEO                   115
#define IDF_VIDEO_PARAMS                116
#define IDC_EDIT_DEWARP_NAME            117
#define IDR_MAINFRAME                   118
#define IDR_ICANDITYPE                  119
#define IDC_BUTTON_DEWARP_NAME          120
#define IDD_DLG_PARAMS                  121
#define IDC_SAVE_FULL                   122
#define IDL_CUSTOM_TCA_STATUS           123
#define ID_AOM_RED_SWITCH               131
#define IDD_DLG_DESINUSOID              132
#define IDC_STIMULUS_SETUP              133
#define IDC_TCA_SETUP                   134
#define ID_FRAME_FOUR                   135
#define IDB_TCA_MEASURE                 136
#define IDC_TCA_APPLY                   137
#define IDC_TCA_OVERRIDE                138
#define IDL_TCA_RED_LBL                 139
#define IDL_TCA_GR_LBL                  140
#define IDL_TCA_X_LBL                   141
#define IDL_TCA_Y_LBL                   142
#define IDE_TCA_RED_X                   143
#define IDE_TCA_RED_Y                   144
#define IDE_TCA_GR_X                    145
#define IDE_TCA_GR_Y                    146
#define ID_STIMULUS_PREDICTION_LABEL    147
#define ID_STIMULUS_PREDICTION_SLIDER   148
#define IDC_LABEL_PREFIX                149
#define IDC_EDITBOX_PREFIX              150
#define IDC_LABEL_VIDEOLEN              151
#define IDC_EDITBOX_VIDEOLEN            152
#define ID_FLASH_FREQ_SLIDER            153
#define ID_FLASH_DUTY_SLIDER            154
#define IDW_SOUND                       155
#define IDD_FADINGEPARAMS               156
#define ID_FLASH_FREQ_LABEL             157
#define IDW_DING                        158
#define ID_DELIVERY_MODE_LABEL          159
#define IDC_LASER_CONTROL               160
#define ID_RED_RADIO                    161
#define ID_IR_RADIO                     162
#define IDC_LASER_POWER_SLIDER          163
#define IDC_EDITBOX_LASERPOWER          164
#define IDC_LABEL_LASERPOWER            165
#define IDC_LABEL_LASERPOWERTL          166
#define ID_FLASH_DUTY_LABEL             167
#define IDC_LABEL_FEILDSIZE             168
#define IDC_EDITBOX_FIELDSIZE           169
#define ID_DEWARP_CAPTION               170
#define ID_DEWARP_POSLIST               171
#define ID_DEWARP_TIME                  172
#define ID_DEWARP_ILLUMINATION          173
#define ID_DEWARP_GO                    174
#define ID_DEWARP_FILLING1              175
#define ID_DEWARP_FILLING2              176
#define ID_DEWARP_STIMNUM_LABEL_X       177
#define ID_DEWARP_STIMNUM_EDIT_X        178
#define ID_DEWARP_UPDATE_LIST           179
#define ID_DEWARP_FILLING3              180
#define ID_LOAD_STIMULUS                181
#define ID_DEWARP_STIMNUM_EDIT_Y        182
#define IDC_LABEL_LASERSLIDERPOS        183
#define ID_DEWARP_STIMNUM_LABEL_Y       184
#define ID_DEWARP_CELLSIZE_EDIT_X       185
#define ID_DEWARP_CELLSIZE_EDIT_Y       186
#define ID_DEWARP_CELLSIZE_LABEL_X      187
#define ID_DEWARP_CELLSIZE_LABEL_Y      188
#define ID_PREDICTION_TIME_LABEL        189
#define ID_FLASH_FREQUENCY_LABEL        190
#define ID_FLASH_DUTYCYCLE_LABEL        191
#define ID_DELIVERY_MODE1               192
#define ID_DELIVERY_MODE2               193
#define ID_DELIVERY_MODE3               194
#define ID_STAB_RADIO                   199
#define ID_HIST_RADIO                   200
#define ID_TAB_CONTROLLER               201
#define ID_FRAME_ONE                    202
#define ID_FRAME_TWO                    203
#define ID_FRAME_THREE                  204
#define ID_AOM_IR_SWITCH                205
#define ID_LOAD_MULTI_STIM              206
#define IDC_REDGR_ADJUST_Y              209
#define ID_STIMULUS_REWIND              215
#define ID_STIM_GAIN_CONTROL            216
#define ID_STIM_GAIN_LBL                217
#define ID_PUPIL_MASK                   225
#define ID_STIM_GAIN_VALUE_LBL          231
#define ID_RED_CALIBRATION              235
#define ID_ONE_FRAME_DELAY              237
#define ID_GREEN_RADIO                  238
#define IDC_LASER_POWER_14BITS          241
#define ID_ANIMATE_CTRL                 242
#define IDC_PROCESSOR_USED              248
#define ID_AOM_GREEN_SWITCH             249
#define ID_MASK_GAIN_CONTROL            250
#define ID_MASK_GAIN_VALUE_LBL          251
#define ID_MASK_GAIN_LBL                252
#define ID_VOLTS_PER_DEG_LABEL          253
#define ID_VOLTS_PER_DEG_SLIDER         254
#define IDC_VOLTS_PER_DEG_Y             255
#define ID_MOTION_SCALER_VALUE_LABEL    256
#define ID_MOTION_ANGLE_LABEL           257
#define ID_MOTION_ANGLE_SLIDER          258
#define IDC_MOTION_ANGLE_Y              259
#define ID_MOTION_ANGLE_VALUE_LABEL     260
#define IDC_EDIT_PATCH_CNT              1002
#define IDC_FRAME_X                     1004
#define IDC_CHECK_DESINUSOID            1004
#define IDC_FRAME_Y                     1005
#define IDC_FRAME_WARP                  1006
#define IDC_FRAME_UNWARP                1007
#define IDC_LIST_PARAMS                 1008
#define IDC_LOAD_GRIDS                  1008
#define IDC_BUTTON_ADD                  1009
#define IDC_RUN_DESINU                  1009
#define IDC_BUTTON_UP                   1010
#define IDC_SAVE_LUT                    1010
#define IDC_EDIT_PAT_X                  1011
#define IDC_FRAME_ID_MSG                1011
#define IDC_FRAME_ID                    1012
#define IDC_START_FRAME                 1013
#define IDC_END_FRAME                   1014
#define IDC_FREQ_HORZ                   1015
#define IDC_EDIT_FREQ_HORZ              1016
#define IDC_EDIT_PAT_Y                  1017
#define IDC_FREQ_VERT                   1017
#define IDC_EDIT_L_XDIM                 1018
#define IDC_EDIT_FREQ_VERT              1018
#define IDC_EDIT_L_YDIM                 1019
#define IDC_GRID_SIZE                   1019
#define IDC_EDIT_L_YDIM_0               1020
#define IDC_EDIT_GRID_SIZE              1020
#define IDC_GRID_NUMBER                 1021
#define IDC_EDIT_GRID_NUMB              1022
#define IDC_RICHEDIT1                   1022
#define IDC_EDIT_X_OFFSET               1024
#define IDC_EDIT_Y_OFFSET               1025
#define IDC_EDIT_X_SHIFT                1026
#define IDC_EDIT_Y_SHIFT                1027
#define IDC_BUTTON_REMOVE               1028
#define IDC_BUTTON_DOWN                 1029
#define IDC_BUTTON_UPDATE               1030
#define IDC_BUTTON_LUT                  1031
#define IDC_EDIT_K1                     1033
#define IDC_EDIT_GTHRESH                1034
#define IDC_EDIT_SRCTHRESH              1035
#define IDC_EDIT_LAYER_CNT              1036
#define IDC_EDIT_ITER_NUM               1037
#define IDC_EDIT_F_XDIM                 1038
#define IDC_EDIT_F_YDIM                 1039
#define IDC_SCROLLBAR_X                 1044
#define IDC_SCROLLBAR_Y                 1045
#define IDC_HV_GRID                     1046
#define IDC_PIX_PER_DEGX                1047
#define IDC_PIX_PER_DEGY                1048
#define IDC_PIX_PER_DEGX1               1049
#define IDC_PIX_PER_DEGY1               1050
#define IDL_LOWGAIN                     1051
#define IDE_LOWGAIN                     1052
#define IDL_HIGHGAIN                    1053
#define IDE_HIGHGAIN                    1054
#define IDL_STEPSIZE                    1055
#define IDE_STEPSIZE                    1056
#define IDL_MESSAGE                     1057
#define IDL_MESSAGE2                    1058
#define IDC_COMBO_FILTER                1059
#define IDL_MESSAGE3                    1060
#define IDC_CHECK_SLR                   1061
#define ID_BUTTON_OLD_REF               1062
#define IDC_GPU_DEV_LIST                1063
#define ID_BUTTON_GAIN0_TRACK           1064
#define IDC_CHECK2                      1065
#define IDC_IR_GAIN1                    1066
#define IDC_CHECK_INVERTTRACES          1067
#define IDC_SYNC_OCT                    1068
#define IDC_RED_GAIN1                   1069
#define IDC_GR_GAIN1                    1070
#define IDC_BLUE_GAIN1                  1071
#define IDC_IR_GAIN2                    1072
#define IDC_RED_GAIN2                   1073
#define IDC_GR_GAIN2                    1074
#define IDC_BLUE_GAIN2                  1075
#define IDC_CHECK3                      1076
#define IDC_TURN_ON_OFF                 1077
#define IDL_BRIGHTNESS                  1078
#define IDS_BRIGHTNESS                  1079
#define IDL_CONTRAST                    1080
#define IDS_BRIGHTNESS2                 1081
#define IDS_CONTRAST                    1081
#define IDL_STATIC                      1082
#define ID_STABLIZE_GO                  32773
#define ID_STABLIZE_SUSPEND             32775
#define ID_SETUP_DESINUSOID             32776
#define ID_SETUP_PARAMS                 32777
#define ID_CAMERA_CONNECT               32779
#define ID_CAMERA_DISCONNECT            32780
#define ID_Menu                         32782
#define ID_SETUP_SAVEREF                32783
#define ID_STABLIZE_LOAD_EXT_REF        32784
#define ID_SETUP_MOVIENORMALIZE         32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           250
#endif
#endif
